export const ITEMS = {
    // Logs
    normal_logs: { name: "Normal Logs" },
    oak_logs: { name: "Oak Logs" },
    willow_logs: { name: "Willow Logs" },
    maple_logs: { name: "Maple Logs" },
    yew_logs: { name: "Yew Logs" },

    // Raw fish
    raw_shrimp: { name: "Raw Shrimp" },
    raw_sardine: { name: "Raw Sardine" },
    raw_karambwanji: { name: "Raw Karambwanji" },
    raw_herring: { name: "Raw Herring" },
    raw_anchovies: { name: "Raw Anchovies" },
    raw_mackerel: { name: "Raw Mackerel" },
    raw_trout: { name: "Raw Trout" },
    raw_bream: { name: "Raw Bream" },
    raw_cod: { name: "Raw Cod" },
    raw_pike: { name: "Raw Pike" },
    raw_slimy_eel: { name: "Raw Slimy Eel" },
    raw_salmon: { name: "Raw Salmon" },
    raw_tuna: { name: "Raw Tuna" },
    raw_lobster: { name: "Raw Lobster" },
    raw_bass: { name: "Raw Bass" },
    raw_swordfish: { name: "Raw Swordfish" },
    raw_monkfish: { name: "Raw Monkfish" },
    raw_karambwan: { name: "Raw Karambwan" },
    raw_shark: { name: "Raw Shark" },
    raw_anglerfish: { name: "Raw Anglerfish" },
    raw_dark_crab: { name: "Raw Dark Crab" },
};
