export const ITEMS = {
    coins: { name: "Coins" },

    dramen_staff: { name: "Dramen staff" },
    // Logs
    logs: { name: "Logs" },
    oak_logs: { name: "Oak logs" },
    willow_logs: { name: "Willow logs" },
    maple_logs: { name: "Maple logs" },
    yew_logs: { name: "Yew logs" },

    arrow_shaft: { name: "Arrow shaft" },
    headless_arrow: { name: "Headless arrow" },

    // General supplies
    bucket: { name: "Bucket" },
    pot: { name: "Pot" },
    jug: { name: "Jug" },
    bowl: { name: "Bowl" },
    shears: { name: "Shears" },
    tinderbox: { name: "Tinderbox" },
    chisel: { name: "Chisel" },
    hammer: { name: "Hammer" },
    knife: { name: "Knife" },

    // Fishing equipment
    small_fishing_net: { name: "Small fishing net" },
    fishing_rod: { name: "Fishing rod" },
    fly_fishing_rod: { name: "Fly fishing rod" },
    lobster_pot: { name: "Lobster pot" },
    harpoon: { name: "Harpoon" },
    big_fishing_net: { name: "Big fishing net" },
    fishing_bait: { name: "Fishing bait" },
    feather: { name: "Feather" },

    // Axes
    bronze_axe: { name: "Bronze axe" },
    iron_axe: { name: "Iron axe" },
    steel_axe: { name: "Steel axe" },
    mithril_axe: { name: "Mithril axe" },
    adamant_axe: { name: "Adamant axe" },

    // Pickaxes
    bronze_pickaxe: { name: "Bronze pickaxe" },
    iron_pickaxe: { name: "Iron pickaxe" },
    steel_pickaxe: { name: "Steel pickaxe" },
    mithril_pickaxe: { name: "Mithril pickaxe" },
    adamant_pickaxe: { name: "Adamant pickaxe" },

    // Quest rewards
    silverlight: { name: "Silverlight" },
    amulet_of_accuracy: { name: "Amulet of accuracy" },

    // Raw fish
    raw_shrimps: { name: "Raw shrimps" },
    raw_sardine: { name: "Raw sardine" },
    raw_karambwanji: { name: "Raw karambwanji" },
    raw_herring: { name: "Raw herring" },
    raw_anchovies: { name: "Raw anchovies" },
    raw_mackerel: { name: "Raw mackerel" },
    raw_trout: { name: "Raw trout" },
    raw_bream: { name: "Raw bream" },
    raw_cod: { name: "Raw cod" },
    raw_pike: { name: "Raw pike" },
    raw_slimy_eel: { name: "Raw slimy eel" },
    raw_salmon: { name: "Raw salmon" },
    raw_tuna: { name: "Raw tuna" },
    raw_lobster: { name: "Raw lobster" },
    raw_bass: { name: "Raw bass" },
    raw_swordfish: { name: "Raw swordfish" },
    raw_monkfish: { name: "Raw monkfish" },
    raw_karambwan: { name: "Raw karambwan" },
    raw_shark: { name: "Raw shark" },
    raw_anglerfish: { name: "Raw anglerfish" },
    raw_dark_crab: { name: "Raw dark crab" },

    shrimps: { name: "Shrimps" },
    sardine: { name: "Sardine" },
    karambwanji: { name: "Karambwanji" },
    herring: { name: "Herring" },
    anchovies: { name: "Anchovies" },
    mackerel: { name: "Mackerel" },
    trout: { name: "Trout" },
    bream: { name: "Bream" },
    cod: { name: "Cod" },
    pike: { name: "Pike" },
    slimy_eel: { name: "Slimy eel" },
    salmon: { name: "Salmon" },
    tuna: { name: "Tuna" },
    lobster: { name: "Lobster" },
    bass: { name: "Bass" },
    swordfish: { name: "Swordfish" },
    monkfish: { name: "Monkfish" },
    karambwan: { name: "Karambwan" },
    shark: { name: "Shark" },
    anglerfish: { name: "Anglerfish" },
    dark_crab: { name: "Dark crab" },

    rune_essence: {name: "Rune essence"},
    copper_ore: {name: "Copper ore"},
    tin_ore: {name: "Tin ore"},
    limestone: {name: "limestone"},
    blurite_ore: {name: "Blurite ore"},
    iron_ore: {name: "Iron ore"},
    silver_ore: {name: "Silver ore"},
    volcanic_ash: {name: "Volcanic ash"},
    pure_essence: {name: "Pure essence"},
    coal: {name: "Coal"},
    sandstone: {name: "Sandstone"},
    uncut_sapphire: {name: "Uncut sapphire"},
    gold_ore: {name: "Gold ore"},
    calcified_rock: {name: "Calcified rock"},
    granite: {name: "Granite"},
    mithril_ore: {name: "Mithril ore"},
    adamantite_ore: {name: "Adamantite ore"},
    ancient_essence: {name: "Ancient essence"},
    runite_ore: {name: "Runite ore"},

    bronze_bar: { name: "Bronze bar" },
    iron_bar: { name: "Iron bar" },
    silver_bar: { name: "Silver bar" },
    elemental_bar: { name: "Elemental bar" },
    steel_bar: { name: "Steel bar" },
    gold_bar: { name: "Gold bar" },
    lovakite_bar: { name: "Lovakite bar" },
    mithril_bar: { name: "Mithril bar" },
    adamantite_bar: { name: "Adamantite bar" },
    runite_bar: { name: "Runite bar" },

    cake: {name: "Cake"},
    bread: {name: "Bread"},
    silk: {name: "Silk"},

    air_rune: {name: "Air rune"},
    mind_rune: {name: "Mind rune"},
    water_rune: {name: "Water rune"},
    earth_rune: {name: "Earth rune"},
    fire_rune: {name: "Fire rune"},
    body_rune: {name: "Body rune"},
    cosmic_rune: {name: "Cosmic rune"},
    chaos_rune: {name: "Chaos rune"},
    nature_rune: {name: "Nature rune"},
    law_rune: {name: "Law rune"},
    death_rune: {name: "Death rune"},

    // Grimy herbs (Friendly Forager relic)
    grimy_guam_leaf:   { name: "Grimy guam leaf" },
    grimy_marrentill:  { name: "Grimy marrentill" },
    grimy_tarromin:    { name: "Grimy tarromin" },
    grimy_harralander: { name: "Grimy harralander" },
    grimy_ranarr_weed: { name: "Grimy ranarr weed" },
    grimy_toadflax:    { name: "Grimy toadflax" },
    grimy_irit_leaf:   { name: "Grimy irit leaf" },
    grimy_avantoe:     { name: "Grimy avantoe" },
    grimy_kwuarm:      { name: "Grimy kwuarm" },
    grimy_snapdragon:  { name: "Grimy snapdragon" },
    grimy_cadantine:   { name: "Grimy cadantine" },
    grimy_lantadyme:   { name: "Grimy lantadyme" },
    grimy_dwarf_weed:  { name: "Grimy dwarf weed" },
    grimy_torstol:     { name: "Grimy torstol" },

    bronze_dagger: { name: "Bronze dagger" },
    bronze_sword: { name: "Bronze sword" },
    wooden_shield: { name: "Wooden shield" },
    shortbow: { name: "Shortbow" },
    bronze_arrow: { name: "Bronze arrow" }
};


export const STARTER_ITEMS = {
    coins: 25,
    dramen_staff: 1,
    bronze_axe: 1,
    bronze_pickaxe: 1,
    tinderbox: 1,
    shrimps: 1, 
    bronze_dagger: 1,
    bronze_sword: 1,
    wooden_shield: 1,
    shortbow: 1,
    bronze_arrow: 25,
    air_rune: 25,
    mind_rune: 15,
    bucket: 1,
    pot: 1,
    bread: 1,
    water_rune: 6,
    earth_rune: 4,
    body_rune: 2
};
