export const SHOPS = {
    general_store: {
        name: "General Store",
        inventory: [
            { item: "bucket", price: 2 },
            { item: "pot", price: 1 },
            { item: "jug", price: 1 },
            { item: "bowl", price: 4 },
            { item: "shears", price: 1 },
            { item: "tinderbox", price: 1 },
            { item: "chisel", price: 9 },
            { item: "hammer", price: 13 },
            { item: "knife", price: 6 },
        ],
    },
    fishing_shop: {
        name: "Fishing Supplies",
        inventory: [
            { item: "small_fishing_net", price: 5 },
            { item: "fishing_rod", price: 5 },
            { item: "fly_fishing_rod", price: 5 },
            { item: "lobster_pot", price: 20 },
            { item: "harpoon", price: 45 },
            { item: "big_fishing_net", price: 36 },
            { item: "fishing_bait", price: 3 },
            { item: "feather", price: 2 },
        ],
    },
    tal_teklan_rune_shop: {
        name: "Tal Teklan Rune Shop",
        inventory: [
            { item: "air_rune", price: 4},
            { item: "water_rune", price: 4},
            { item: "earth_rune", price: 4},
            { item: "fire_rune", price: 4},
            { item: "mind_rune", price: 3},
            { item: "body_rune", price: 3},
            { item: "chaos_rune", price: 90},
            { item: "death_rune", price: 180},
            { item: "cosmic_rune", price: 50},
            { item: "nature_rune", price: 180},
            { item: "air_rune_pack", price: 430},
            { item: "water_rune_pack", price: 430},
            { item: "earth_rune_pack", price: 430},
            { item: "fire_rune_pack", price: 430},
            { item: "mind_rune_pack", price: 330},
            { item: "chaos_rune_pack", price: 9950},
        ],
    },
    lunami_s_axe_shop: {
        name: "Lunami's Axe Shop",
        inventory: [
            { item: "bronze_axe", price: 16},
            { item: "iron_axe", price: 56},
            { item: "steel_axe", price: 200},
            { item: "mithril_axe", price: 520},
            { item: "adamant_axe", price: 1280},
            { item: "bronze_battleaxe", price: 52},
            { item: "iron_battleaxe", price: 182},
            { item: "steel_battleaxe", price: 650},
            { item: "mithril_battleaxe", price: 1690},
            { item: "adamant_battleaxe", price: 4160},
        ]
    },
    sebamo_s_sublime_staffs: {
        name: "Sebamo's Sublime Staffs",
        inventory: [
            { item: "staff", price: 15},
            { item: "magic_staff", price: 200},
            { item: "staff_of_air", price: 1500},
            { item: "staff_of_water", price: 1500},
            { item: "staff_of_earth", price: 1500},
            { item: "staff_of_fire", price: 1500},
        ]
    },
    obli_s_general_store: {
        name: "Obli's General Store",
        inventory: [
            { item: "tinderbox", price: 1},
            { item: "vial", price: 3},
            { item: "empty_vial_pack", price: 300},
            { item: "pestle_and_mortar", price: 6},
            { item: "pot", price: 1},
            { item: "bronze_axe", price: 24},
            { item: "bronze_pickaxe", price: 1},
            { item: "iron_axe", price: 84},
            { item: "leather_body", price: 31},
            { item: "leather_gloves", price: 9},
            { item: "leather_boots", price: 9},
            { item: "cooked_meat", price: 6},
            { item: "bread", price: 18},
            { item: "bronze_bar", price: 12},
            { item: "spade", price: 4},
            { item: "candle", price: 4},
            { item: "unlit_torch", price: 6},
            { item: "chisel", price: 1},
            { item: "hammer", price: 1},
            { item: "papyrus", price: 15},
            { item: "charcoal", price: 67},
            { item: "vial_of_water", price: 3},
            { item: "water-filled_vial_pack", price: 301},
            { item: "machete", price: 60},
            { item: "rope", price: 27},
        ]
    },
    trader_stan_s_trading_post: {
        name: "Trader Stan's Trading Post",
        inventory: [
            { item: "pot", price: 2},
            { item: "jug", price: 2},
            { item: "empty_jug_pack", price: 350},
            { item: "shears", price: 2},
            { item: "bucket", price: 5},
            { item: "empty_bucket_pack", price: 1250},
            { item: "bowl", price: 10},
            { item: "cake_tin", price: 25},
            { item: "tinderbox", price: 2},
            { item: "chisel", price: 2},
            { item: "hammer", price: 2},
            { item: "newcomer_map", price: 2},
            { item: "security_book", price: 5},
            { item: "rope", price: 45},
            { item: "knife", price: 15},
            { item: "pineapple", price: 5},
            { item: "banana", price: 5},
            { item: "orange", price: 5},
            { item: "bucket_of_slime", price: 2},
            { item: "glassblowing_pipe", price: 5},
            { item: "bucket_of_sand", price: 5},
            { item: "seaweed", price: 5},
            { item: "soda_ash", price: 5},
            { item: "lobster_pot", price: 50},
            { item: "fishing_rod", price: 12},
            { item: "swamp_paste", price: 75},
            { item: "tyras_helm", price: 1375},
            { item: "raw_rabbit", price: 50},
            { item: "right_eye_patch", price: 5},
            { item: "bronze_cannonball", price: 5},
        ]
    },
    toci_s_gem_store: {
        name: "Toci's Gem Store",
        inventory: [
            { item: "uncut_sapphire", price: 25},
            { item: "uncut_emerald", price: 50},
            { item: "uncut_ruby", price: 100},
            { item: "uncut_diamond", price: 200},
            { item: "sapphire", price: 250},
            { item: "emerald", price: 500},
            { item: "ruby", price: 1000},
            { item: "diamond", price: 2000},
        ]
    },
};

export const SHOP_LIST = Object.entries(SHOPS).map(([key, shop]) => ({
    key,
    name: shop.name,
}));
