export const SKILL_METHODS = {
    woodcutting: {
        label: "Woodcutting",
        methods: [
            { key: "chop_regular_trees", name: "Regular Trees", xpPerAction: 25, actionLabel: "log", itemYields: [{ item: "logs", quantity: 1 }]},
            { key: "chop_oak_trees", name: "Oak Trees", xpPerAction: 37.5, actionLabel: "log", itemYields: [{ item: "oak_logs", quantity: 1 }]},
            { key: "chop_willow_trees", name: "Willow Trees", xpPerAction: 67.5, actionLabel: "log", itemYields: [{ item: "willow_logs", quantity: 1 }]},
            { key: "chop_maple_trees", name: "Maple Trees", xpPerAction: 100, actionLabel: "log", itemYields: [{ item: "maple_logs", quantity: 1 }]},
            { key: "chop_yew_trees", name: "Yew Trees", xpPerAction: 175, actionLabel: "log", itemYields: [{ item: "yew_logs", quantity: 1 }]},

        ],
    },
    firemaking: {
        label: "Firemaking",
        methods: [
            { key: "burn_logs", name: "Normal Logs", xpPerAction: 40, actionLabel: "log", itemCosts: [{ item: "logs", quantity: 1 }] },
            { key: "burn_oak_logs", name: "Oak Logs", xpPerAction: 60, actionLabel: "log", itemCosts: [{ item: "oak_logs", quantity: 1 }] },
            { key: "burn_willow_logs", name: "Willow Logs", xpPerAction: 90, actionLabel: "log", itemCosts: [{ item: "willow_logs", quantity: 1 }] },
            { key: "burn_maple_logs", name: "Maple Logs", xpPerAction: 135, actionLabel: "log", itemCosts: [{ item: "maple_logs", quantity: 1 }] },
            { key: "burn_yew_logs", name: "Yew Logs", xpPerAction: 202.5, actionLabel: "log", itemCosts: [{ item: "yew_logs", quantity: 1 }] },
        ],
    },
    fishing: {
        label: "Fishing",
        methods: [
            { key: "catch_shrimp", name: "Catch Shrimp", xpPerAction: 10, actionLabel: "fish", itemYields: [{ item: "raw_shrimps", quantity: 1 }] },
            { key: "catch_sardine", name: "Catch Sardine", xpPerAction: 20, actionLabel: "fish", itemYields: [{ item: "raw_sardine", quantity: 1 }] },
            { key: "catch_karambwanji", name: "Catch Karambwanji", xpPerAction: 5, actionLabel: "fish", itemYields: [{ item: "raw_karambwanji", quantity: 1 }] },
            { key: "catch_herring", name: "Catch Herring", xpPerAction: 30, actionLabel: "fish", itemYields: [{ item: "raw_herring", quantity: 1 }] },
            { key: "catch_anchovies", name: "Catch Anchovies", xpPerAction: 40, actionLabel: "fish", itemYields: [{ item: "raw_anchovies", quantity: 1 }] },
            { key: "catch_mackerel", name: "Catch Mackerel", xpPerAction: 20, actionLabel: "fish", itemYields: [{ item: "raw_mackerel", quantity: 1 }] },
            { key: "catch_trout", name: "Catch Trout", xpPerAction: 50, actionLabel: "fish", itemYields: [{ item: "raw_trout", quantity: 1 }] },
            { key: "catch_bream", name: "Catch Bream", xpPerAction: 20, actionLabel: "fish", itemYields: [{ item: "raw_bream", quantity: 1 }] },
            { key: "catch_cod", name: "Catch Cod", xpPerAction: 45, actionLabel: "fish", itemYields: [{ item: "raw_cod", quantity: 1 }] },
            { key: "catch_pike", name: "Catch Pike", xpPerAction: 60, actionLabel: "fish", itemYields: [{ item: "raw_pike", quantity: 1 }] },
            { key: "catch_slimy eel", name: "Catch Slimy eel", xpPerAction: 80, actionLabel: "fish", itemYields: [{ item: "raw_slimy_eel", quantity: 1 }] },
            { key: "catch_salmon", name: "Catch Salmon", xpPerAction: 70, actionLabel: "fish", itemYields: [{ item: "raw_salmon", quantity: 1 }] },
            { key: "catch_frog spawn", name: "Catch Frog spawn", xpPerAction: 75, actionLabel: "fish" },
            { key: "catch_tuna", name: "Catch Tuna", xpPerAction: 80, actionLabel: "fish", itemYields: [{ item: "raw_tuna", quantity: 1 }] },
            { key: "catch_rainbow fish", name: "Catch Rainbow fish", xpPerAction: 80, actionLabel: "fish" },
            { key: "catch_cave eel", name: "Catch Cave eel", xpPerAction: 80, actionLabel: "fish" },
            { key: "catch_lobster", name: "Catch Lobster", xpPerAction: 90, actionLabel: "fish", itemYields: [{ item: "raw_lobster", quantity: 1 }] },
            { key: "catch_bass", name: "Catch Bass", xpPerAction: 100, actionLabel: "fish", itemYields: [{ item: "raw_bass", quantity: 1 }] },
            { key: "catch_swordfish", name: "Catch Swordfish", xpPerAction: 100, actionLabel: "fish", itemYields: [{ item: "raw_swordfish", quantity: 1 }] },
            { key: "catch_lava eel", name: "Catch Lava eel", xpPerAction: 60, actionLabel: "fish" },
            { key: "catch_monkfish", name: "Catch Monkfish", xpPerAction: 120, actionLabel: "fish", itemYields: [{ item: "raw_monkfish", quantity: 1 }] },
            { key: "catch_karambwan", name: "Catch Karambwan", xpPerAction: 50, actionLabel: "fish", itemYields: [{ item: "raw_karambwan", quantity: 1 }] },
            { key: "catch_shark", name: "Catch Shark", xpPerAction: 110, actionLabel: "fish", itemYields: [{ item: "raw_shark", quantity: 1 }] },
            { key: "catch_sea turtle", name: "Catch Sea turtle", xpPerAction: 38, actionLabel: "fish" },
            { key: "catch_infernal eel (smashed)", name: "Catch Infernal eel (smashed)", xpPerAction: 95, actionLabel: "fish" },
            { key: "catch_manta ray", name: "Catch Manta ray", xpPerAction: 69, actionLabel: "fish" },
            { key: "catch_anglerfish", name: "Catch Anglerfish", xpPerAction: 120, actionLabel: "fish", itemYields: [{ item: "raw_anglerfish", quantity: 1 }] },
            { key: "catch_dark crab", name: "Catch Dark crab", xpPerAction: 130, actionLabel: "fish", itemYields: [{ item: "raw_dark_crab", quantity: 1 }] },
        ],
    },
    cooking: {
        label: "Cooking",
        methods: [
            { key: "cook_shrimp", name: "Cook Shrimp", xpPerAction: 30, actionLabel: "cook", itemCosts: [{ item: "raw_shrimps", quantity: 1 }], itemYields: [{ item: "shrimps", quantity: 1 }] },
            { key: "cook_sardine", name: "Cook Sardine", xpPerAction: 40, actionLabel: "cook", itemCosts: [{ item: "raw_sardine", quantity: 1 }], itemYields: [{ item: "sardine", quantity: 1 }] },
            { key: "cook_karambwanji", name: "Cook Karambwanji", xpPerAction: 10, actionLabel: "cook", itemCosts: [{ item: "raw_karambwanji", quantity: 1 }], itemYields: [{ item: "karambwanji", quantity: 1 }] },
            { key: "cook_herring", name: "Cook Herring", xpPerAction: 50, actionLabel: "cook", itemCosts: [{ item: "raw_herring", quantity: 1 }], itemYields: [{ item: "herring", quantity: 1 }] },
            { key: "cook_anchovies", name: "Cook Anchovies", xpPerAction: 30, actionLabel: "cook", itemCosts: [{ item: "raw_anchovies", quantity: 1 }], itemYields: [{ item: "anchovies", quantity: 1 }] },
            { key: "cook_mackerel", name: "Cook Mackerel", xpPerAction: 60, actionLabel: "cook", itemCosts: [{ item: "raw_mackerel", quantity: 1 }], itemYields: [{ item: "mackerel", quantity: 1 }] },
            { key: "cook_trout", name: "Cook Trout", xpPerAction: 70, actionLabel: "cook", itemCosts: [{ item: "raw_trout", quantity: 1 }], itemYields: [{ item: "trout", quantity: 1 }] },
            { key: "cook_bream", name: "Cook Bream", xpPerAction: 45, actionLabel: "cook", itemCosts: [{ item: "raw_bream", quantity: 1 }], itemYields: [{ item: "bream", quantity: 1 }] },
            { key: "cook_cod", name: "Cook Cod", xpPerAction: 75, actionLabel: "cook", itemCosts: [{ item: "raw_cod", quantity: 1 }], itemYields: [{ item: "cod", quantity: 1 }] },
            { key: "cook_pike", name: "Cook Pike", xpPerAction: 80, actionLabel: "cook", itemCosts: [{ item: "raw_pike", quantity: 1 }], itemYields: [{ item: "pike", quantity: 1 }] },
            { key: "cook_slimy_eel", name: "Cook Slimy eel", xpPerAction: 95, actionLabel: "cook", itemCosts: [{ item: "raw_slimy_eel", quantity: 1 }], itemYields: [{ item: "slimy_eel", quantity: 1 }] },
            { key: "cook_salmon", name: "Cook Salmon", xpPerAction: 90, actionLabel: "cook", itemCosts: [{ item: "raw_salmon", quantity: 1 }], itemYields: [{ item: "salmon", quantity: 1 }] },
            { key: "cook_rainbow_fish", name: "Cook Rainbow fish", xpPerAction: 110, actionLabel: "cook" },
            { key: "cook_cave_eel", name: "Cook Cave eel", xpPerAction: 115, actionLabel: "cook" },
            { key: "cook_lobster", name: "Cook Lobster", xpPerAction: 120, actionLabel: "cook", itemCosts: [{ item: "raw_lobster", quantity: 1 }], itemYields: [{ item: "lobster", quantity: 1 }] },
            { key: "cook_bass", name: "Cook Bass", xpPerAction: 130, actionLabel: "cook", itemCosts: [{ item: "raw_bass", quantity: 1 }], itemYields: [{ item: "bass", quantity: 1 }] },
            { key: "cook_common_tench", name: "Cook Common tench", xpPerAction: 10, actionLabel: "cook" },
            { key: "cook_karambwan", name: "Cook Karambwan", xpPerAction: 190, actionLabel: "cook", itemCosts: [{ item: "raw_karambwan", quantity: 1 }], itemYields: [{ item: "karambwan", quantity: 1 }] },
            { key: "cook_giant_krill", name: "Cook Giant krill", xpPerAction: 177.5, actionLabel: "cook" },
            { key: "cook_sea_turtle", name: "Cook Sea turtle", xpPerAction: 212, actionLabel: "cook" },
            { key: "cook_yellowfin", name: "Cook Yellowfin", xpPerAction: 200, actionLabel: "cook" },
            { key: "cook_manta_ray", name: "Cook Manta ray", xpPerAction: 216, actionLabel: "cook", itemCosts: [{ item: "raw_manta_ray", quantity: 1 }], itemYields: [{ item: "manta_ray", quantity: 1 }] },
            { key: "cook_shark", name: "Cook Shark", xpPerAction: 200, actionLabel: "cook", itemCosts: [{ item: "raw_shark", quantity: 1 }], itemYields: [{ item: "shark", quantity: 1 }] },
            { key: "cook_anglerfish", name: "Cook Anglerfish", xpPerAction: 230, actionLabel: "cook", itemCosts: [{ item: "raw_anglerfish", quantity: 1 }], itemYields: [{ item: "anglerfish", quantity: 1 }] },
            { key: "cook_dark_crab", name: "Cook Dark crab", xpPerAction: 215, actionLabel: "cook", itemCosts: [{ item: "raw_dark_crab", quantity: 1 }], itemYields: [{ item: "dark_crab", quantity: 1 }] },
        ]
    },
    fletching: {
        label: "Fletching",
        methods: [
            { key: "fletch_fletch_arrow_shafts_logs", name: "Fletch Fletch Arrow Shafts (Logs)", xpPerAction: 5, actionLabel: "fletch", itemCosts: [{ item: "logs", quantity: 1 }], itemYields: [{ item: "arrow_shaft", quantity: 15 }] },
            { key: "fletch_headless_arrows", name: "Fletch Headless Arrows", xpPerAction: 1, actionLabel: "fletch", itemCosts: [{ item: "arrow_shaft", quantity: 15 }, { item: "feather", quantity: 15 }], itemYields: [{ item: "headless_arrow", quantity: 15 }] },
            { key: "fletch_shortbow_u", name: "Fletch Shortbow (u)", xpPerAction: 5, actionLabel: "fletch", itemCosts: [{ item: "logs", quantity: 1 }], itemYields: [{ item: "shortbow_u", quantity: 1 }] },
        ],
    },
    thieving: {
        label: "Thieving",
        methods: [
            { key: "pickpocket_men", name: "Pickpocket Men", xpPerAction: 8, actionLabel: "pickpocket", itemYields: [{ item: "coins", quantity: 3 }]},
            { key: "pickpocket_farmer", name: "Pickpocket Farmer", xpPerAction: 14.5, actionLabel: "pickpocket", itemYields: [{ item: "coins", quantity: 3 }]},
            { key: "pickpocket_ham_member", name: "Pickpocket HAM Member", xpPerAction: 22.2, actionLabel: "pickpocket", lootTableKey: "ham_member" },
            { key: "pickpocket_warrior", name: "Pickpocket Warrior", xpPerAction: 26, actionLabel: "pickpocket", itemYields: [{ item: "coins", quantity: 3 }]},
            { key: "pickpocket_digsite_workman", name: "Pickpocket Digsite workman", xpPerAction: 10.4, actionLabel: "pickpocket", itemYields: [{ item: "coins", quantity: 3 }]},
            { key: "pickpocket_villager", name: "Pickpocket Villager", xpPerAction: 8, actionLabel: "pickpocket", itemYields: [{ item: "coins", quantity: 3 }]},
            { key: "pickpocket_rogue", name: "Pickpocket Rogue", xpPerAction: 36.5, actionLabel: "pickpocket", itemYields: [{ item: "coins", quantity: 3 }]},
            { key: "pickpocket_cave_goblin", name: "Pickpocket Cave goblin", xpPerAction: 40, actionLabel: "pickpocket", itemYields: [{ item: "coins", quantity: 3 }]},
            { key: "pickpocket_master_farmer", name: "Pickpocket Master Farmer", xpPerAction: 43, actionLabel: "pickpocket", itemYields: [{ item: "coins", quantity: 3 }]},
            { key: "pickpocket_guard", name: "Pickpocket Guard", xpPerAction: 46.8, actionLabel: "pickpocket", itemYields: [{ item: "coins", quantity: 30 }]},
            { key: "pickpocket_fremennik_citizen", name: "Pickpocket Fremennik Citizen", xpPerAction: 65, actionLabel: "pickpocket", itemYields: [{ item: "coins", quantity: 30 }]},
            { key: "pickpocket_bearded_pollnivnian_bandit", name: "Pickpocket Bearded Pollnivnian Bandit", xpPerAction: 65, actionLabel: "pickpocket", itemYields: [{ item: "coins", quantity: 30 }]},
            { key: "pickpocket_wealthy_citizen", name: "Pickpocket Wealthy citizen", xpPerAction: 96, actionLabel: "pickpocket", itemYields: [{ item: "coins", quantity: 30 }, { item: "house_keys", quantity: 1, chance: 1/17 }]},
            { key: "pickpocket_desert_bandit", name: "Pickpocket Desert Bandit", xpPerAction: 79.4, actionLabel: "pickpocket", itemYields: [{ item: "coins", quantity: 30 }]},
            { key: "pickpocket_pollnivnian_bandit", name: "Pickpocket Pollnivnian Bandit", xpPerAction: 84.3, actionLabel: "pickpocket", itemYields: [{ item: "coins", quantity: 30 }]},
            { key: "pickpocket_knight", name: "Pickpocket Knight", xpPerAction: 84.3, actionLabel: "pickpocket", itemYields: [{ item: "coins", quantity: 30 }]},
            { key: "pickpocket_pirate", name: "Pickpocket Pirate", xpPerAction: 72, actionLabel: "pickpocket", itemYields: [{ item: "coins", quantity: 30 }]},
            { key: "pickpocket_yanille_watchman", name: "Pickpocket Yanille Watchman", xpPerAction: 137.5, actionLabel: "pickpocket", itemYields: [{ item: "coins", quantity: 30 }]},
            { key: "pickpocket_menaphite_thug", name: "Pickpocket Menaphite Thug", xpPerAction: 137.5, actionLabel: "pickpocket", itemYields: [{ item: "coins", quantity: 30 }]},
            { key: "pickpocket_paladin", name: "Pickpocket Paladin", xpPerAction: 131.8, actionLabel: "pickpocket", itemYields: [{ item: "coins", quantity: 30 }]},
            { key: "pickpocket_gnome", name: "Pickpocket Gnome", xpPerAction: 133.3, actionLabel: "pickpocket", itemYields: [{ item: "coins", quantity: 30 }]},
            { key: "pickpocket_hero", name: "Pickpocket Hero", xpPerAction: 163.3, actionLabel: "pickpocket", itemYields: [{ item: "coins", quantity: 30 }]},
            { key: "pickpocket_vyre", name: "Pickpocket Vyre", xpPerAction: 306.9, actionLabel: "pickpocket", itemYields: [{ item: "coins", quantity: 30 }]},
            { key: "pickpocket_elf", name: "Pickpocket Elf", xpPerAction: 353.3, actionLabel: "pickpocket", itemYields: [{ item: "coins", quantity: 30 }]},
            { key: "pickpocket_tzhaar-hur", name: "Pickpocket TzHaar-Hur", xpPerAction: 103.4, actionLabel: "pickpocket", itemYields: [{ item: "coins", quantity: 30 }]},
            { key: "steal_from_vegetable_stall", name: "Steal From Vegetable stall", xpPerAction: 10, actionLabel: "steal from" },
            { key: "steal_from_bakery_stall", name: "Steal From Bakery stall", xpPerAction: 16, actionLabel: "steal from", itemYields: [{item: "cake", quantity: 1}] },
            { key: "steal_from_tea_stall", name: "Steal From Tea stall", xpPerAction: 16, actionLabel: "steal from" },
            { key: "steal_from_monkey_food_stall", name: "Steal From Monkey food stall", xpPerAction: 16, actionLabel: "steal from" },
            { key: "steal_from_crafting_stall", name: "Steal From Crafting stall", xpPerAction: 20, actionLabel: "steal from" },
            { key: "steal_from_monkey_general_stall", name: "Steal From Monkey general stall", xpPerAction: 25, actionLabel: "steal from" },
            { key: "steal_from_silk_stall", name: "Steal From Silk stall", xpPerAction: 24, actionLabel: "steal from", itemYields: [{ item: "silk", quantity: 1 }] },
            { key: "steal_from_wine_stall", name: "Steal From Wine stall", xpPerAction: 27, actionLabel: "steal from" },
            { key: "steal_from_fruit_stall", name: "Steal From Fruit Stall", xpPerAction: 28.5, actionLabel: "steal from" },
            { key: "steal_from_seed_stall", name: "Steal From Seed stall", xpPerAction: 10, actionLabel: "steal from" },
            { key: "steal_from_fur_stall", name: "Steal From Fur stall", xpPerAction: 45, actionLabel: "steal from" },
            { key: "steal_from_fish_stall", name: "Steal From Fish stall", xpPerAction: 42, actionLabel: "steal from" },
            { key: "steal_from_crossbow_stall", name: "Steal From Crossbow stall", xpPerAction: 52, actionLabel: "steal from" },
            { key: "steal_from_silver_stall", name: "Steal From Silver stall", xpPerAction: 205, actionLabel: "steal from" },
            { key: "steal_from_spice_stall", name: "Steal From Spice stall", xpPerAction: 92, actionLabel: "steal from" },
            { key: "steal_from_magic_stall", name: "Steal From Magic stall", xpPerAction: 90, actionLabel: "steal from" },
            { key: "steal_from_scimitar_stall", name: "Steal From Scimitar stall", xpPerAction: 210, actionLabel: "steal from" },
            { key: "steal_from_gem_stall", name: "Steal From Gem stall", xpPerAction: 408, actionLabel: "steal from" },
            { key: "steal_from_cannonball_stall", name: "Steal From Cannonball stall", xpPerAction: 223, actionLabel: "steal from" },
        ],
    },
    mining: {
        label: "Mining",
        methods: [
            { key: "mine_rune_essence", name: "Mine Rune essence", xpPerAction: 5, actionLabel: "mine", itemYields: [{ item: "rune_essence", quantity: 1 }] },
            { key: "mine_copper", name: "Mine Copper", xpPerAction: 17.5, actionLabel: "mine", itemYields: [{ item: "copper_ore", quantity: 1 }] },
            { key: "mine_tin", name: "Mine Tin", xpPerAction: 17.5, actionLabel: "mine", itemYields: [{ item: "tin_ore", quantity: 1 }] },
            { key: "mine_limestone", name: "Mine Limestone", xpPerAction: 26.5, actionLabel: "mine", itemYields: [{ item: "limestone", quantity: 1 }] },
            { key: "mine_blurite", name: "Mine Blurite", xpPerAction: 17.5, actionLabel: "mine", itemYields: [{ item: "blurite_ore", quantity: 1 }] },
            { key: "mine_iron", name: "Mine Iron", xpPerAction: 35, actionLabel: "mine", itemYields: [{ item: "iron_ore", quantity: 1 }] },
            { key: "mine_silver", name: "Mine Silver", xpPerAction: 40, actionLabel: "mine", itemYields: [{ item: "silver_ore", quantity: 1 }] },
            { key: "mine_volcanic_ash", name: "Mine Volcanic ash", xpPerAction: 10, actionLabel: "mine", itemYields: [{ item: "volcanic_ash", quantity: 1 }] },
            { key: "mine_pure_essence", name: "Mine Pure essence", xpPerAction: 5, actionLabel: "mine", itemYields: [{ item: "pure_essence", quantity: 1 }] },
            { key: "mine_coal", name: "Mine Coal", xpPerAction: 50, actionLabel: "mine", itemYields: [{ item: "coal", quantity: 1 }] },
            { key: "mine_sandstone", name: "Mine Sandstone", xpPerAction: 30, actionLabel: "mine", itemYields: [{ item: "sandstone", quantity: 1 }] },
            { key: "mine_gem_rocks", name: "Mine Gem rocks", xpPerAction: 65, actionLabel: "mine", itemYields: [{ item: "uncut_sapphire", quantity: 1 }] },
            { key: "mine_gold", name: "Mine Gold", xpPerAction: 65, actionLabel: "mine", itemYields: [{ item: "gold_ore", quantity: 1 }] },
            { key: "mine_calcified_rocks", name: "Mine Calcified rocks", xpPerAction: 33, actionLabel: "mine", itemYields: [{ item: "calcified_rock", quantity: 1 }] },
            { key: "mine_granite", name: "Mine Granite", xpPerAction: 50, actionLabel: "mine", itemYields: [{ item: "granite", quantity: 1 }] },
            { key: "mine_mithril", name: "Mine Mithril", xpPerAction: 80, actionLabel: "mine", itemYields: [{ item: "mithril_ore", quantity: 1 }] },
            { key: "mine_adamantite", name: "Mine Adamantite", xpPerAction: 95, actionLabel: "mine", itemYields: [{ item: "adamantite_ore", quantity: 1 }] },
            { key: "mine_ancient_essence", name: "Mine Ancient essence", xpPerAction: 13.5, actionLabel: "mine", itemYields: [{ item: "ancient_essence", quantity: 1 }] },
            { key: "mine_runite", name: "Mine Runite", xpPerAction: 125, actionLabel: "mine", itemYields: [{ item: "runite_ore", quantity: 1 }] },
        ]
    },
    smithing: {
        label: "Smithing",
        methods: [
            { key: "smelt_bronze", name: "Smelt Bronze", xpPerAction: 6.2, actionLabel: "smelt", itemCosts: [{ item: "copper_ore", quantity: 1 }, { item: "tin_ore", quantity: 1 }], itemYields: [{ item: "bronze_bar", quantity: 1 }] },
            { key: "smith_bronze", name: "Smith Bronze", xpPerAction: 12.5, actionLabel: "smith", itemCosts: [{ item: "bronze_bar", quantity: 1}]},
            { key: "smelt_iron", name: "Smelt Iron", xpPerAction: 12.5, actionLabel: "smelt", itemCosts: [{ item: "iron_ore", quantity: 1 }], itemYields: [{ item: "iron_bar", quantity: 1, chance: 1/2 }]},
            { key: "smith_iron", name: "Smith Iron", xpPerAction: 25, actionLabel: "smith", itemCosts: [{ item: "iron_bar", quantity: 1}]},
            { key: "smelt_silver", name: "Smelt Silver", xpPerAction: 13.7, actionLabel: "smelt", itemCosts: [{ item: "silver_ore", quantity: 1 }], itemYields: [{ item: "silver_bar", quantity: 1 }]},
            { key: "smelt_elemental", name: "Smelt Elemental", xpPerAction: 7.5, actionLabel: "smelt" },
            { key: "smelt_steel", name: "Smelt Steel", xpPerAction: 17.5, actionLabel: "smelt", itemCosts: [{ item: "iron_ore", quantity: 1}, { item: "coal", quantity: 2 }], itemYields: [{ item: "steel_bar", quantity: 1 }]},
            { key: "smith_steel", name: "Smith Steel", xpPerAction: 37.5, actionLabel: "smith", itemCosts: [{ item: "steel_bar", quantity: 1}]},
            { key: "smelt_gold", name: "Smelt Gold", xpPerAction: 22.5, actionLabel: "smelt" },
            { key: "smelt_lovakite", name: "Smelt Lovakite", xpPerAction: 20, actionLabel: "smelt" },
            { key: "smelt_mithril", name: "Smelt Mithril", xpPerAction: 30, actionLabel: "smelt" },
            { key: "smith_mithril", name: "Smith Mithril", xpPerAction: 50, actionLabel: "smith", itemCosts: [{ item: "mithril_bar", quantity: 1}]},
            { key: "smelt_adamantite", name: "Smelt Adamantite", xpPerAction: 37.5, actionLabel: "smelt" },
            { key: "smith_adamantite", name: "Smith Adamantite", xpPerAction: 62.5, actionLabel: "smith", itemCosts: [{ item: "adamantite_bar", quantity: 1}]},
            { key: "smelt_runite", name: "Smelt Runite", xpPerAction: 50, actionLabel: "smelt" },
            { key: "smith_runite", name: "Smith Runite", xpPerAction: 75, actionLabel: "smith", itemCosts: [{ item: "runite_bar", quantity: 1}]},
        ]
    }
};

export function getSkillOptions() {
    return Object.entries(SKILL_METHODS).map(([key, value]) => ({
        key,
        label: value.label,
    }));
}

export function getMethodsForSkill(skillKey) {
    if (!skillKey || !SKILL_METHODS[skillKey]) {
        return [];
    }

    return SKILL_METHODS[skillKey].methods;
}

export function getMethod(skillKey, methodKey) {
    return getMethodsForSkill(skillKey).find((method) => method.key === methodKey);
}
